### ISSUE TITLE
Direct deprecation thrown with doctrine/dbal 3.6.6

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#499]
when upgrading to doctrine/dbal:3.6.6, the `ResetDatabase` triggers some deprecations, which are considered as direct (maybe because we're using a trait? :thinking: )

```
Subscribing to postConnect events is deprecated. Implement a middleware instead. (Connection.php:385 called by Connection.php:1652, https://github.com/doctrine/dbal/issues/5784, package doctrine/dbal)
Stack trace:
#0 [internal function]: Symfony\Bridge\PhpUnit\DeprecationErrorHandler->handleError(16384, '...', '...', 209)
#1 vendor/doctrine/dbal/src/Connection.php(385): Doctrine\Deprecations\Deprecation::trigger('...', '...', '...', '...')
#2 vendor/doctrine/dbal/src/Connection.php(1652): Doctrine\DBAL\Connection->connect()
#3 vendor/doctrine/dbal/src/Connection.php(1079): Doctrine\DBAL\Connection->getWrappedConnection()
#4 vendor/doctrine/dbal/src/Connection.php(899): Doctrine\DBAL\Connection->executeQuery('...', Array, Array)
#5 vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php(109): Doctrine\DBAL\Connection->fetchAllAssociative('...')
#6 vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php(86): Doctrine\DBAL\Tools\Console\Command\RunSqlCommand->runQuery(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Doctrine\DBAL\Connection), '...')
#7 vendor/doctrine/doctrine-bundle/Command/Proxy/RunSqlDoctrineCommand.php(42): Doctrine\DBAL\Tools\Console\Command\RunSqlCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#8 vendor/symfony/console/Command/Command.php(326): Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#9 vendor/symfony/console/Application.php(1081): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#10 vendor/symfony/framework-bundle/Console/Application.php(91): Symfony\Component\Console\Application->doRunCommand(Object(Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#11 vendor/symfony/console/Application.php(320): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#12 vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#13 vendor/symfony/console/Application.php(174): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#14 vendor/zenstruck/foundry/src/Test/AbstractSchemaResetter.php(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#15 vendor/zenstruck/foundry/src/Test/ORMDatabaseResetter.php(110): Zenstruck\Foundry\Test\AbstractSchemaResetter->runCommand(Object(Symfony\Bundle\FrameworkBundle\Console\Application), '...', Array, true)
#16 vendor/zenstruck/foundry/src/Test/ORMDatabaseResetter.php(49): Zenstruck\Foundry\Test\ORMDatabaseResetter->dropAndResetDatabase()
#17 vendor/zenstruck/foundry/src/Test/DatabaseResetter.php(48): Zenstruck\Foundry\Test\ORMDatabaseResetter->resetDatabase()
#18 vendor/zenstruck/foundry/src/Test/ResetDatabase.php(53): Zenstruck\Foundry\Test\DatabaseResetter::resetDatabase(Object(App\Infrastructure\Common\Symfony\Kernel), true)
#19 vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestSuite.php(619): App\Tests\Infrastructure\APIOS\ImportEditoMessageTest::_resetDatabase()
#20 vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#21 vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#22 vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#23 vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#24 vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#25 vendor/bin/.phpunit/phpunit-9.5-0/phpunit(22): PHPUnit\TextUI\Command::main()
#26 vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(467): include('...')
```

**Comment by kbond** [comment]
Is this still valid?

**Comment by nikophil** [comment]
I think this was a bug in doctrine
