### ISSUE TITLE
Can't install foundry in Symfony 3.4

### ISSUE THREAD

**Issue by TavoNiievez** [zenstruck/foundry#88]
I don't really know which versions of Symfony are supported by Foundry, but this error appears after trying to install in a new 3.4 project
```
Symfony operations: 1 recipe (f5b976f91fc829a4840e75cc8dfc3701)
  - Configuring zenstruck/foundry (>=v1.5.0): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of c
lass "Symfony\Component\Config\Definition\Builder\TreeBuilder". in C:\...\vendor\zenstruck\foundry\src\Bundle\DependencyInjection\Configuration
.php on line 17
!!
!!  Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Componen
t\Config\Definition\Builder\TreeBuilder". in C:\...\vendor\zenstruck\foundry\src\Bundle\DependencyInjection\Configuration.php on line 17
!!
!!  Call Stack:
!!      0.4020   12135240   1. Symfony\Component\Debug\ErrorHandler->handleException() C:\...\vendor\symfony\debug\ErrorHandler.php:0
!!
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode"
 of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in C:\...\vendor\zenstruck\foundry\src\Bundle\DependencyInjection\Configur
ation.php:17
!!  Stack trace:
!!  #0 C:\...\vendor\symfony\config\Definition\Processor.php(50): Zenstruck\Foundry\Bundle\DependencyInjection\Configuration->getConfigTreeBuil
der()
!!  #1 C:\...\vendor\symfony\dependency-injection\Extension\Extension.php(102): Symfony\Component\Config\Definition\Processor->processConfigura
tion(Object(Zenstruck\Foundry\Bundle\DependencyInjection\Configuration), Array)
!!  #2 C:\...\vendor\symfony\http-kernel\DependencyInjection\ConfigurableExtension.php(35): Symfony\Component\DependencyInjection\Extension\Ext
ension->processConfiguration(Object(Zenstruck\Foundry\Bundle\DependencyInjection\Configuration), Array)
!!  #3 C:\...\vendor\symfony\dependency-injection\Compiler\MergeExtensionConfigurationPass.php(71): S in C:\...\vendor\zenstruck\foundry\s
rc\Bundle\DependencyInjection\Configuration.php on line 17
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

in any case a mention of the supported versions in the readme would be very useful.

**Comment by kbond** [comment]
This is a bit of a tricky one.. The "base" functionality of foundry is usable in 3.4 but the helper traits and bundle is not. Are you intending to use in your tests or fixtures?

**Comment by TavoNiievez** [comment]
> Are you intending to use in your tests or fixtures?

Only for fixtures.

**Comment by kbond** [comment]
Ok, in that case, I think something like this will work:

```php
use Doctrine\Persistence\ManagerRegistry;
use Zenstruck\Foundry\Factory;
use Zenstruck\Foundry\Configuration;

class AppFixtures extends Fixture
{
    public function __construct(ManagerRegistry $registry)
    {
        $config = new Configuration();
        $config->setManagerRegistry($registry);
        // see Configuration class to see the other config options

        Factory::boot($config);
    }

    public function load(ObjectManager $manager)
    {
        // ... use foundry here
    }
}
```

**Comment by TavoNiievez** [comment]
thanks!
but my problem is directly in the installation.
`cache:clear` breaks after `composer require` and Foundry is never installed correctly.

**Comment by kbond** [comment]
Do you have the bundle enabled?

**Comment by TavoNiievez** [comment]
OK, to be clear:

I'm using the 4.4 dir structure which is the one that `symfony new` installs by default.

After executing `composer require zenstruck/foundry --dev` and getting the error described in this issue the bundle is still enabled in `bundles.php`, but the problem persists if i run `symfony console cache:clear` immediately afterwards.

**Comment by kbond** [comment]
Ok, remove `Zenstruck\Foundry\ZenstruckFoundryBundle::class => ['dev' => true, 'test' => true],` from `bundles.php` the cache:clear again.

**Comment by kbond** [comment]
You're welcome. Be aware that the method I describe above is sort of a hack and uses internal functionality that may change in a future release.You'd be best to lock foundry at your current version until you can upgrade to Symfony 4.4+.

**Comment by TavoNiievez** [comment]
I'll keep it in mind, thanks again :)
